import type { Metadata } from "next";
import localFont from "next/font/local";

import "./globals.css";
import StoreProvider from "./StoreProvider";
import { Toaster } from "react-hot-toast";
import Header from "@/components/header";

export const metadata: Metadata = {
  title: "Next Ecommerce App",
  description: "Generated by create next app",
};

const shabnam = localFont({
  src: [
    {
      path: "../fonts/Shabnam-Light-FD.woff2",
      weight: "400",
      style: "light",
    },
    {
      path: "../fonts/Shabnam-Medium-FD.woff2",
      weight: "500",
      style: "normal",
    },
    {
      path: "../fonts/Shabnam-Bold-FD.woff2",
      weight: "700",
      style: "bold",
    },
  ],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" dir="rtl">
      <StoreProvider>
        <body className={shabnam.className}>
          <Toaster position="top-left" />
          <Header />
          <div className="py-10 max-md:px-4 px-[60px]">{children}</div>
        </body>
      </StoreProvider>
    </html>
  );
}
